export const types = {

  GET_TODO_START: "GET_TODO_START",
  GET_TODO_SUCCESS: "GET_TODO_SUCCESS",
  GET_TODO_FAILD: "GET_TODO_FAILD",

  ADD_TODO_START: "ADD_TODO_START",
  ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
  ADD_TODO_FAILD: "ADD_TODO_FAILD",

  REMOVE_TODO_START: "REMOVE_TODO_START",
  REMOVE_TODO_SUCCESS: "REMOVE_TODO_SUCCESS",
  REMOVE_TODO_FAILD: "REMOVE_TODO_FAILD",

};

